### PR TITLE
Start to fix the build

### PR DESCRIPTION
**Pull request by philip-peterson**
Hi there, I was curious about Sauron and started to try to run the examples. I realized then that the compilation is broken in several places. This PR starts to fix some of it (working around the failing warnings). I didn't finish because there were changes to `Http::fetch_with_text_response_decoder` which I don't understand (and also it was getting to my bedtime). Would be interested in working with someone on fixing these.

### CODE REVIEW

**Comment by philip-peterson** [comment]
This fixes at least the SSR example now.

**Comment by ivanceras** [comment]
Thank you @philip-peterson for this PR. 
> I was curious about Sauron and started to try to run the examples. I realized then that the compilation is broken in several places.

My bad, I usually compile the example in each of their own directory, that's why the path dependency to the framework is relative to each of the examples.



> Http::fetch_with_text_response_decoder

In the function definition
```rust
    pub fn fetch_with_text_response_decoder<APP, MSG, DE, CB, ERRCB, OUT>(
        url: &str,
        response_text_decoder: DE,
        cb: CB,
        err_cb: ERRCB,
    ) -> Cmd<APP, MSG>

```
Generally, this just wraps an http request which expects to return a text response. A function to decode the text response is also passed. So when a text response from the server is received, it will be decoded with the `response_text_decoder` function, which is defined by `Fn(String) -> OUT + Clone + 'static`. The OUT is a generic type which is the return type of your `response_text_decoder` function.  The cb (Callback) is defined with `Fn(Result<OUT, Response>) -> MSG + Clone + 'static` which means, it should be a function which accepts a result of either OUT on success or Response when errored.

In the `fetch-data` example.
```rust
Http::fetch_with_text_response_decoder(
    &url,
    |v: String| {
        let data: Result<Data, _> = serde_json::from_str(&v);
        trace!("data: {:#?}", data);
        data.expect("Error deserializing data")
    },
    Msg::ReceivedData,
    Msg::RequestError,
)

```
The 2nd argument on the function call is a closure which accepts a string and return a `Data`.
The output `Data` is then further passed into the callback function `Msg::ReceivedData` since enums qualifies as functions.

Alternatively this callback could also be written in a longer form:
```rust
|res: Result<Data,Response>| {
    Msg::ReceivedData(res)
}
```

**Comment by philip-peterson** [comment]
Ok, thanks for the update. Is there anything blocking this PR from being merged?

**Comment by ivanceras** [comment]
If you have nothing more to add to this PR. I'll merge it.

**Pull request merged**
